; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp_wroom_02]
platform = espressif8266
board = esp_wroom_02
framework = arduino
board_build.filesystem = littlefs
board_build.ldscript = eagle.flash.2m256.ld
monitor_speed = 115200
upload_speed = 921600
; OTAアップロード時は下の2行を有効化してupload_speedをコメントアウト
; upload_protocol = espota
; upload_port = smoker.local    ; or IP address

lib_deps =
    ESP8266WebServer
    ArduinoJson

[env:m5stack-core2]
platform = espressif32
board = m5stack-core2
framework = arduino
board_build.filesystem = littlefs
monitor_speed = 115200
upload_speed = 921600

lib_deps =
    ArduinoJson
